
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 07 18:51:05 CST 2019
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Nombre = 16;
  public static final int Entero = 56;
  public static final int Padre = 54;
  public static final int ModificarPagina = 50;
  public static final int BorrarPagina = 45;
  public static final int Id = 4;
  public static final int Derecha = 23;
  public static final int Atributo = 14;
  public static final int VideoComponente = 57;
  public static final int TextColor = 5;
  public static final int Clase = 55;
  public static final int Izquierda = 40;
  public static final int ModificarComponente = 39;
  public static final int UsuarioCreacion = 36;
  public static final int TituloComponente = 12;
  public static final int Etiquetas = 28;
  public static final int ImagenComponente = 34;
  public static final int BorrarSitioWeb = 43;
  public static final int Titulo = 51;
  public static final int Color = 11;
  public static final int MenuComponente = 48;
  public static final int UsuarioModificacion = 42;
  public static final int Valor = 29;
  public static final int Acciones = 13;
  public static final int BorrarComponente = 46;
  public static final int Etiqueta = 3;
  public static final int Diagonal = 26;
  public static final int EOF = 0;
  public static final int Sitio = 53;
  public static final int MayorQue = 27;
  public static final int error = 1;
  public static final int Accion = 7;
  public static final int Texto = 9;
  public static final int Justificar = 47;
  public static final int ErrorLexico = 6;
  public static final int Atributos = 15;
  public static final int ParrafoComponente = 25;
  public static final int URL = 20;
  public static final int Origen = 22;
  public static final int AtributoEtiquetas = 33;
  public static final int Alineacion = 41;
  public static final int Parametros = 31;
  public static final int DatoEntreComillas = 8;
  public static final int Centrar = 24;
  public static final int NuevaPagina = 44;
  public static final int Identificador = 2;
  public static final int Ancho = 10;
  public static final int Altura = 21;
  public static final int MenorQue = 18;
  public static final int Parametro = 30;
  public static final int AgregarComponente = 49;
  public static final int FechaCreacion = 37;
  public static final int Fecha = 19;
  public static final int ValorParametro = 32;
  public static final int Pagina = 52;
  public static final int Igual = 17;
  public static final int FechaModificacion = 38;
  public static final int NuevoSitioWeb = 35;
}

